--------------------------------------------------------
--  File created - Thursday-March-07-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View V_CYLY_ORA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APP_DATA_TRAINEE"."V_CYLY_ORA" ("THEDATE", "THEYEAR", "THEMONTH", "THEMONTH_YYYYMMM", "CY_LY") AS 
  select add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       ) as THEDATE,
       extract(YEAR from add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       )) as THEYEAR,
       extract(MONTH from add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       )) as THEMONTH,
       CASE WHEN extract(MONTH from add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       ))>9 THEN CONCAT(CONCAT(extract(YEAR from add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       )),'/M'),extract(MONTH from add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       ))) ELSE CONCAT(CONCAT(extract(YEAR from add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       )),'/M0'),extract(MONTH from add_months (   
         ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),  
         level - 1  
       ))) END AS THEMONTH_YYYYMMM,
       CASE WHEN add_months(ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),level - 1)>=ADD_MONTHS(TRUNC(SYSDATE,'MM'),-12) THEN 'CY' 
            WHEN add_months(ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),level - 1)>=ADD_MONTHS(TRUNC(SYSDATE,'MM'),-24) THEN 'LY' 
            WHEN add_months(ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),level - 1)>=ADD_MONTHS(TRUNC(SYSDATE,'MM'),-36) THEN 'PY' 
            WHEN add_months(ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38),level - 1)>=ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38) THEN 'XY' 
       END AS CY_LY
from   dual  
connect by level <= months_between (  
  LAST_DAY(SYSDATE),  
  ADD_MONTHS(TRUNC(SYSDATE,'MM'),-38)   
) + 1
;
REM INSERTING into APP_DATA_TRAINEE.V_CYLY_ORA
SET DEFINE OFF;
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JAN-21','DD-MON-RR'),2021,1,'2021/M01','XY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-FEB-21','DD-MON-RR'),2021,2,'2021/M02','XY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-MAR-21','DD-MON-RR'),2021,3,'2021/M03','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-APR-21','DD-MON-RR'),2021,4,'2021/M04','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-MAY-21','DD-MON-RR'),2021,5,'2021/M05','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JUN-21','DD-MON-RR'),2021,6,'2021/M06','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JUL-21','DD-MON-RR'),2021,7,'2021/M07','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-AUG-21','DD-MON-RR'),2021,8,'2021/M08','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-SEP-21','DD-MON-RR'),2021,9,'2021/M09','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-OCT-21','DD-MON-RR'),2021,10,'2021/M10','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-NOV-21','DD-MON-RR'),2021,11,'2021/M11','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-DEC-21','DD-MON-RR'),2021,12,'2021/M12','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JAN-22','DD-MON-RR'),2022,1,'2022/M01','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-FEB-22','DD-MON-RR'),2022,2,'2022/M02','PY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-MAR-22','DD-MON-RR'),2022,3,'2022/M03','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-APR-22','DD-MON-RR'),2022,4,'2022/M04','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-MAY-22','DD-MON-RR'),2022,5,'2022/M05','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JUN-22','DD-MON-RR'),2022,6,'2022/M06','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JUL-22','DD-MON-RR'),2022,7,'2022/M07','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-AUG-22','DD-MON-RR'),2022,8,'2022/M08','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-SEP-22','DD-MON-RR'),2022,9,'2022/M09','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-OCT-22','DD-MON-RR'),2022,10,'2022/M10','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-NOV-22','DD-MON-RR'),2022,11,'2022/M11','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-DEC-22','DD-MON-RR'),2022,12,'2022/M12','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JAN-23','DD-MON-RR'),2023,1,'2023/M01','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-FEB-23','DD-MON-RR'),2023,2,'2023/M02','LY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-MAR-23','DD-MON-RR'),2023,3,'2023/M03','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-APR-23','DD-MON-RR'),2023,4,'2023/M04','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-MAY-23','DD-MON-RR'),2023,5,'2023/M05','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JUN-23','DD-MON-RR'),2023,6,'2023/M06','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JUL-23','DD-MON-RR'),2023,7,'2023/M07','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-AUG-23','DD-MON-RR'),2023,8,'2023/M08','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-SEP-23','DD-MON-RR'),2023,9,'2023/M09','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-OCT-23','DD-MON-RR'),2023,10,'2023/M10','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-NOV-23','DD-MON-RR'),2023,11,'2023/M11','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-DEC-23','DD-MON-RR'),2023,12,'2023/M12','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-JAN-24','DD-MON-RR'),2024,1,'2024/M01','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-FEB-24','DD-MON-RR'),2024,2,'2024/M02','CY');
Insert into APP_DATA_TRAINEE.V_CYLY_ORA (THEDATE,THEYEAR,THEMONTH,THEMONTH_YYYYMMM,CY_LY) values (to_date('01-MAR-24','DD-MON-RR'),2024,3,'2024/M03','CY');
